- name: copy the mongo file
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repo.d/mongo.repo
- name: install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
- name: enabling mongodb
  ansible.builtin.service:
   name: mongod
   enabled: yes
   state: started
- name: remote accept
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'