- name: nodejs installation
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs
- name: import app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup
- name: mongo load
  ansible.builtin.import_role:
   name: common
   tasks_from: mongodb-load