- name: user add
  ansible.builtin.user:
    name: roboshop
- name: making directory
  ansible.builtin.file:
   path: /app
   state: directory
- name: "download {{component}}application"
  ansible.builtin.get_url:
   url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
   dest: /tmp
- name: extract the application
  ansible.builtin.unarchive:
   src: "/tmp/{{component}}.zip"
   dest: /app
   remote_src: yes