- name: disabling nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y


- name: enabling and starting nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present