- name: disabling nodejs
  ansible.buitin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
- name: enabling nodejs
  ansible.builtin.package:
    name: nodejs
    enabled: yes
    state: started